services:
  lb:
    image: traefik:v3
    restart: unless-stopped
    ports:
      - 9000:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      # Enable Traefik Web UI (Use authentication in production)
      - "--api.insecure=true"

      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: "/api"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
    restart: unless-stopped
    scale: 3

  backend:
    build: ./backend
    environment:
      DATABASE_HOST: db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
    restart: unless-stopped
    scale: 2
    # depends_on:
    #   - db

  db:
    image: postgres:17
    volumes:
      - db-vol:/var/lib/postgresql/data:rw
      - ./db:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_PASSWORD=top-secret
      - POSTGRES_DB=expense_tracker
      - POSTGRES_USER=expense_tracker

volumes:
  db-vol:
