services:
  lb:
    image: traefik:v3
    restart: unless-stopped
    ports:
      - 9000:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      # Enable Traefik Web UI (Use authentication in production)
      - "--api.insecure=true"

      - "--ping=true"
      - "--ping.entryPoint=web"

      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
    labels:
      - "autoheal=true"
    healthcheck:
      test: [ "CMD-SHELL", "wget -q0- http://127.0.0.1:80/ping | grep -q 'OK' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: "/api"
    labels:
      - "autoheal=true"
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
    restart: unless-stopped
    scale: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http:/localhost/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  backend:
    build: ./backend
    environment:
      DATABASE_HOST: db
    labels:
      - "autoheal=true"
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
    restart: unless-stopped
    scale: 2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http:/localhost:5001/" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    # depends_on:
    #   - db

  db:
    image: postgres:17
    volumes:
      - db-vol:/var/lib/postgresql/data:rw
      - ./db:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    labels:
      - "autoheal=true"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER -h 127.0.0.1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  autoheal:
    image: willfarrell/autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  db-vol:
